name: Autopep8 Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  autopep:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.1"

    - name: Install Autopep8
      run: pip install autopep8

    - name: Run Autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive --recursive . > logs/autopep/latest_autopep.log
        if grep -q "no changes made" logs/autopep/latest_autopep.log; then
          echo "Autopep8 Status: success" > badge_status.txt
        else
          echo "Autopep8 Status: failure" > badge_status.txt
          exit 1
        fi

    - name: Commit Badge Update
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add badge_status.txt
        git commit -m "Update Autopep8 badge" || echo "No changes to commit"
        git push