# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.1"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
       pip install pytest pytest-cov
       pytest
    - name: Autopep8
      run: | 
       pip install autopep8
       autopep8 --in-place --aggressive --aggressive --recursive . > logs/autopep/latest_autopep.log
      continue-on-error: false
    
    - name: pylint
      run: | 
       pip install pylint
       pylint $(git ls-files '*.py') 2>&1 | tee logs/pylint/latest_pylint.log
      continue-on-error: false

    - name: bandit
      run: |
        pip install bandit 
        bandit -r . 2>&1 | tee logs/bandit/latest_bandit.log
      continue-on-error: false

    - name: Commit changes made by autopep8
      run: |
       git config user.name 'github-actions[bot]'
       git config user.email 'github-actions[bot]@users.noreply.github.com'
       git add .
       git commit -m "Apply autopep8, populate log files for pylint, autopep and bandit " || echo "No autopep8 changes"
       git push
       grep -q "rated at 10" logs/pylint/latest_pylint.log || exit 1
       grep -q "No issues identified" logs/bandit/latest_bandit.log || exit 1
